import type {GetStaticProps,GetStaticPropsContext , NextPage} from 'next'
import Head from 'next/head'
import Image from "next/image";
import styles from '../styles/Home.module.css'
import {Banner} from "../components/banner";
import {Card} from "../components/card";
import coffeeStores from "../data/coffee-stores.json";

//https://nextjs.org/docs/basic-features/typescript

export  const getStaticProps:GetStaticProps  = async(context)=> {
    return {
        props: {
            CoffeeStoresObj:coffeeStores,
            message: `Next.js is awesome`
        }, // will be passed to the page component as props
    }
}
const Home: NextPage = (props   ) => {
//const Home: NextPage<{CoffeeStoresObj:any,message:string}> = ({CoffeeStoresObj,message}   ) => {
 // console.log('props',props);
    const handleOnBannerBtnClick=()=> {
        console.log('hi banner button')
    }
  return (
    <div className={styles.container}>
      <Head>
        <title> Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Coffee Connoisseur
        </h1>
          <Banner buttonText="View stores nearby!" handleOnClick={handleOnBannerBtnClick}/>
          <div className={styles.heroImage}>
          <Image  src="/static/hero-image.png"
                  width={700}
                  height={400}
                  alt="hero image"/>
          </div>
          {props.CoffeeStoresObj.length &&(
              <div className={styles.cardLayout}>
                  {props.CoffeeStoresObj.map((coffeeStore:any)=>{
                      return(
                          <Card
                              key={coffeeStore.id}
                              name={coffeeStore.name}
                                hrefUrl={`/coffeestore/${coffeeStore.id}`}
                                imageUrl={ coffeeStore.imgUrl ||
                                "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                          />
                      )
                  })}
              </div>
          )}
      </main>
    </div>
  )
}

export default Home
